LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := protobuf
LOCAL_CFLAGS := -DHAVE_PTHREAD
LOCAL_PROTOBUF := $(LOCAL_PATH)/../protobuf
LOCAL_C_INCLUDES := $(LOCAL_PROTOBUF)/src
LOCAL_SRC_FILES := \
  ${LOCAL_PROTOBUF}/src/google/protobuf/arena.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/arenastring.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/extension_set.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/generated_message_table_driven_lite.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/generated_message_util.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/io/coded_stream.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/io/zero_copy_stream.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/io/zero_copy_stream_impl_lite.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/message_lite.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/repeated_field.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/stubs/atomicops_internals_x86_gcc.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/stubs/atomicops_internals_x86_msvc.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/stubs/bytestream.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/stubs/common.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/stubs/int128.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/stubs/io_win32.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/stubs/once.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/stubs/status.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/stubs/statusor.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/stubs/stringpiece.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/stubs/stringprintf.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/stubs/structurally_valid.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/stubs/strutil.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/stubs/time.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/wire_format_lite.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/any.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/any.pb.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/api.pb.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/compiler/importer.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/compiler/parser.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/descriptor.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/descriptor.pb.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/descriptor_database.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/duration.pb.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/dynamic_message.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/empty.pb.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/extension_set_heavy.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/field_mask.pb.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/generated_message_reflection.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/generated_message_table_driven.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/io/gzip_stream.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/io/printer.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/io/strtod.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/io/tokenizer.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/io/zero_copy_stream_impl.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/map_field.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/message.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/reflection_ops.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/service.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/source_context.pb.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/struct.pb.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/stubs/mathlimits.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/stubs/substitute.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/text_format.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/timestamp.pb.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/type.pb.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/unknown_field_set.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/delimited_message_util.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/field_comparator.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/field_mask_util.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/internal/datapiece.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/internal/default_value_objectwriter.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/internal/error_listener.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/internal/field_mask_utility.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/internal/json_escaping.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/internal/json_objectwriter.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/internal/json_stream_parser.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/internal/object_writer.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/internal/proto_writer.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/internal/protostream_objectsource.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/internal/protostream_objectwriter.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/internal/type_info.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/internal/type_info_test_helper.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/internal/utility.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/json_util.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/message_differencer.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/time_util.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/util/type_resolver_util.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/wire_format.cc \
  ${LOCAL_PROTOBUF}/src/google/protobuf/wrappers.pb.cc
include $(BUILD_STATIC_LIBRARY)
